Feature dockercompose integration
taniarascia/laconia pull request #9
Opened 2019-08-13 18:49 UTC by kevin-schmitt

Hi,

I have update last pull request for avoid problem with conflict file.  Like advised by @cristophernic i change credential file with make command.

For test:
`git clone --single-branch --branch feature-dockercompose-integration https://github.com/kevin-schmitt/laconia.git`

Then run command make (i don't test for windows os :))

> make init
> make install-app

2019-08-13 19:09 UTC, taniarascia requested changes
Before this PR can be approved:

1. Please remove all .vscode configuration files
2. Make sure all instructions are correct
3. Fix all merge conflicts

Thank you!

2019-08-13 19:09 UTC, taniarascia commented on README.md
> +- Run `make init` for init containers and config file
This command doesn't exist - your makefile has `init-containers`.

2019-08-13 19:09 UTC, taniarascia commented on src/models/Database.php
> +
Remove unnecessary white space.

2019-08-13 19:09 UTC, taniarascia commented on ~/.vscode-root/Backups/workspaces.json
> +{"rootURIWorkspaces":[],"folderURIWorkspaces":["file:///home/kevin/laconia"],"emptyWorkspaceInfos":[{"backupFolder":"1565722292881"}],"emptyWorkspaces":["1565722292881"]}
Please remove all `~/.vscode-root` files.

2019-08-13 19:09 UTC, taniarascia commented on Makefile
> +	docker-compose exec $(CONTAINER_NAME) /bin/cp -f config/credentials.php config/credentials_back.php
Does this file exist?

2019-08-14 03:03 UTC, kevin-schmitt commented on .gitignore
> -.DS_Store
How i can remove it please?

2019-08-14 03:18 UTC, kevin-schmitt commented
Thanks @taniarascia  for you review,
I have problem for fix white space (.gitignore, IndexController.php, Database.php) have you solution or idea for this please?

Thanks

2019-08-19 12:28 UTC, kevin-schmitt commented
@taniarascia  I finish resolve conflict :)
I update readme for installation, say me if is not clear or if you find problems. 

Thanks.

2019-08-29 03:39 UTC, taniarascia commented
I have everything working except htaccss -> nginx rewrites. Those htaccess rewrites were poorly implemented on my part, which is why it's not easy to migrate to nginx...I'll have to fix it in the future.

2019-08-29 03:39 UTC, merged